spring:
  application:
    name: gateway-service
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
jwt:
  master:
    user: gymmsMasterUser
    secret: gymms